title: "Thiago Meireles"
description: "Site em construção"
url: "https://thiagomeireles.github.io"
baseurl: ""

# --- AQUI ESTÁ O TRUQUE ---
# Usamos a versão v0.14.0 para funcionar no GitHub Pages padrão
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

# Plugins necessários para esse tema funcionar bem
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Configuração da Paginação (para o blog)
paginate: 5
paginate_path: "/blog/page:num/"

# Configurações do Menu (Bulma Clean precisa disso)
#hero_image: /assets/images/hero.jpg # Opcional: imagem de fundo do topo
show_sidebar: true # Se quer barra lateral